# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/mpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrpc/mpc.proto\"\x07\n\x05\x45mpty\"\xc9\x01\n\x08Settings\x12\r\n\x05mpc_N\x18\x01 \x01(\x05\x12\x17\n\x0fmpc_sample_time\x18\x02 \x01(\x02\x12\x16\n\x0e\x62icycle_params\x18\x03 \x01(\x0c\x12\x13\n\x0bn_midpoints\x18\x04 \x01(\x05\x12\x11\n\tmidpoints\x18\x05 \x01(\x0c\x12\x13\n\x0bn_refpoints\x18\x06 \x01(\x05\x12\x11\n\trefpoints\x18\x07 \x01(\x0c\x12\x0e\n\x06use_gp\x18\x08 \x01(\x08\x12\x1d\n\x15\x63onstraint_tightening\x18\t \x01(\x08\"\x1a\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\x05\"A\n\x0cLearningData\x12\x10\n\x08pos_info\x18\x01 \x01(\x0c\x12\x0e\n\x06inputs\x18\x02 \x01(\x0c\x12\x0f\n\x07outputs\x18\x03 \x01(\x0c\"O\n\x07Problem\x12\x15\n\rinitial_state\x18\x01 \x01(\x0c\x12\x11\n\tmax_speed\x18\x02 \x01(\x02\x12\x1a\n\x12\x64\x65lay_compensation\x18\x03 \x01(\x08\"e\n\x08Solution\x12\x15\n\rstate_horizon\x18\x01 \x01(\x0c\x12\x17\n\x0f\x63ontrol_horizon\x18\x02 \x01(\x0c\x12\x18\n\x10track_tighteners\x18\x03 \x01(\x0c\x12\x0f\n\x07success\x18\x04 \x01(\x08\x32\xa9\x01\n\x19ModelPredictiveController\x12)\n\x11initialize_solver\x12\t.Settings\x1a\t.Response\x12\x1c\n\x05solve\x12\x08.Problem\x1a\t.Solution\x12+\n\x0flearn_from_data\x12\r.LearningData\x1a\t.Response\x12\x16\n\x04\x64one\x12\x06.Empty\x1a\x06.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc.mpc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=17
  _globals['_EMPTY']._serialized_end=24
  _globals['_SETTINGS']._serialized_start=27
  _globals['_SETTINGS']._serialized_end=228
  _globals['_RESPONSE']._serialized_start=230
  _globals['_RESPONSE']._serialized_end=256
  _globals['_LEARNINGDATA']._serialized_start=258
  _globals['_LEARNINGDATA']._serialized_end=323
  _globals['_PROBLEM']._serialized_start=325
  _globals['_PROBLEM']._serialized_end=404
  _globals['_SOLUTION']._serialized_start=406
  _globals['_SOLUTION']._serialized_end=507
  _globals['_MODELPREDICTIVECONTROLLER']._serialized_start=510
  _globals['_MODELPREDICTIVECONTROLLER']._serialized_end=679
# @@protoc_insertion_point(module_scope)
